### ISSUE TITLE
media manifests: panic when a media manifest is proxied and no date filters are set

### ISSUE THREAD

**Issue by zsiec** [cbsinteractive/bakery#139]
When testing the new `phe` filter. we're seeing a panic in the logs here: https://github.com/cbsinteractive/bakery/blob/master/filters/hls.go#L412

Calls to `filterRenditionManifest` assume start/end filters exist and attempt to access struct properties without checking if the struct is non-nil.

Aha! Link: https://viacomcbs-digital.aha.io/features/BAKE-34

**Comment by flavioribeiro** [comment]
repro:
```
% http 'http://bakery.cbsi.video/phe(true)/aHR0cHM6Ly9kaWN0YTU0ODczYTIuYWlyc3BhY2UtY2RuLmNic2l2aWRlby5jb20va2VpdGhoOTdoLXRlc3QvZjFlOGUwOGEwZjk2NDkyMzk0ZjRkYmM3YjhjMjJhZGQvZW4ubTN1OA.m3u8'
HTTP/1.1 504 GATEWAY_TIMEOUT
Accept-Ranges: bytes
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: X-CDN
Age: 0
Connection: keep-alive
Content-Length: 0
Content-Type: application/x-mpegURL
Date: Tue, 02 Mar 2021 12:11:12 GMT
Via: 1.1 varnish, 1.1 varnish
X-CDN: Fastly
X-Cache: MISS, MISS
X-Cache-Hits: 0, 0
X-Served-By: cache-mdw17373-MDW, cache-lga21950-LGA
X-Shield: Error 504
X-Timer: S1614687072.191065,VS0,VE112
```

bakery logs:
```
2021/03/02 07:12:48 http: panic serving 127.0.0.1:52194: runtime error: invalid memory address or nil pointer dereference
goroutine 19 [running]:
net/http.(*conn).serve.func1(0xc000212140)
	/usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x14c5920, 0x186bf30)
	/usr/local/go/src/runtime/panic.go:975 +0x47a
github.com/cbsinteractive/bakery/filters.(*HLSFilter).filterRenditionManifest(0xc000172000, 0xc0000c1560, 0xc0000c1b00, 0x162bba0, 0xc0000c1b00, 0x2, 0x0)
	/Users/fribe0409/cbs/bakery/filters/hls.go:412 +0xdc
github.com/cbsinteractive/bakery/filters.(*HLSFilter).FilterContent(0xc000172000, 0x162aae0, 0xc0001e3590, 0xc0000c1560, 0xc0000da798, 0x18ab338, 0x1622580, 0xc0001e3110)
	/Users/fribe0409/cbs/bakery/filters/hls.go:68 +0xa51
github.com/cbsinteractive/bakery/handlers.LoadHandler.func1(0x1f3c898, 0xc0000caf40, 0xc000226200)
	/Users/fribe0409/cbs/bakery/handlers/handler.go:80 +0xa1a
net/http.HandlerFunc.ServeHTTP(0xc000218060, 0x1f3c898, 0xc0000caf40, 0xc000226200)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/cbsinteractive/bakery/config.Config.authMiddleware.func1.1(0x1f3c898, 0xc0000caf40, 0xc000226200)
	/Users/fribe0409/cbs/bakery/config/config.go:118 +0x351
net/http.HandlerFunc.ServeHTTP(0xc0000a93a0, 0x1f3c898, 0xc0000caf40, 0xc000226200)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/rs/zerolog/hlog.RequestIDHandler.func1.1(0x1f3c898, 0xc0000caf40, 0xc000226200)
	/Users/fribe0409/go/pkg/mod/github.com/rs/zerolog@v1.18.0/hlog/hlog.go:169 +0x151
net/http.HandlerFunc.ServeHTTP(0xc0000cad00, 0x1f3c898, 0xc0000caf40, 0xc000226100)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/rs/zerolog/hlog.RemoteAddrHandler.func1.1(0x1f3c898, 0xc0000caf40, 0xc000226100)
	/Users/fribe0409/go/pkg/mod/github.com/rs/zerolog@v1.18.0/hlog/hlog.go:88 +0xc4
net/http.HandlerFunc.ServeHTTP(0xc0001e31d0, 0x1f3c898, 0xc0000caf40, 0xc000226100)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/rs/zerolog/hlog.AccessHandler.func1.1(0x16293e0, 0xc00021c0e0, 0xc000226100)
	/Users/fribe0409/go/pkg/mod/github.com/rs/zerolog@v1.18.0/hlog/hlog.go:196 +0x23b
net/http.HandlerFunc.ServeHTTP(0xc0000a93c0, 0x16293e0, 0xc00021c0e0, 0xc000226100)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/rs/zerolog/hlog.NewHandler.func1.1(0x16293e0, 0xc00021c0e0, 0xc000226000)
	/Users/fribe0409/go/pkg/mod/github.com/rs/zerolog@v1.18.0/hlog/hlog.go:30 +0x3ed
net/http.HandlerFunc.ServeHTTP(0xc00020fdc0, 0x16293e0, 0xc00021c0e0, 0xc000226000)
	/usr/local/go/src/net/http/server.go:2042 +0x44
net/http.(*ServeMux).ServeHTTP(0x187a5e0, 0x16293e0, 0xc00021c0e0, 0xc000226000)
	/usr/local/go/src/net/http/server.go:2417 +0x1ad
net/http.serverHandler.ServeHTTP(0xc00021c000, 0x16293e0, 0xc00021c0e0, 0xc000226000)
	/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc000212140, 0x162aa20, 0xc0000cad80)
	/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2969 +0x36c
```
